@startuml

' 定义模块
component "app-common" as common
component "app-infra" as infra
component "app-runner" as runner
component "app-component" as comp
component "app-test" as test

' 定义依赖关系
runner --> common : uses
runner --> comp : uses

comp --> infra: uses
comp --> common: uses

infra --> common: uses


note top of test
integration test for other module
end note
@enduml